name: Healthcare Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Generate Prisma client
      - name: Prisma generate
        run: yarn prisma generate

      # 5. Run migrations (for production)
      - name: Prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn prisma migrate deploy

      # 6. Build TypeScript project
      - name: Build project
        run: tsc

      # 7. Run tests (optional)
      # - name: Run tests
      #   run: yarn test

      # 8. Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/app
            git pull origin main
            yarn install --frozen-lockfile
            yarn prisma migrate deploy
            tsc
            pm2 restart all
